### PR TITLE
Swap out the language option list for autocomplete search

### PR DESCRIPTION
**Pull request by khanduri**
githunt

### CODE REVIEW

**Comment by kamranahmedse** [comment]
Thanks for taking the time to create PR but I don't think we need that.
Thanks though.

**Comment by khanduri** [comment]
No worries! I liked the idea about githunt, and planned to make a few changes as I see fit. I'll keep it to my own fork for now.

Great work btw!

**Comment by kamranahmedse** [comment]
Thanks, glad that you liked it.

**Comment by suadev** [comment]
@kamranahmedse , Actually it would be very cool. Because there are a lot of language options in the dropdown list.

**Pull request closed without merging**
